import turtle 
t = turtle. Turtle()
t.shape('turtle')
t.speed(100)
radius=int(50)
t.circle(radius)
t.up()
t.goto(100,0)
t.down()
t.circle(radius+20)
t.up()
t.goto(200,0)
t.down()
t.circle(radius+40)
